name: Scheduled Message

on:
    schedule:
        - cron: "0 12 * * *"

jobs:
    print_message:
        runs-on: ubuntu-latest
        steps:
            - name: Exibir mensagem
              run: echo "Bom dia! Essa é uma execução agendada do GitHub Actions."