name: Multi Steps

on:
    push:
        branches:
            - main

jobs:
    primeiro-stage:
        runs-on: ubuntu-latest
        steps:
            - name: Primeiro - Exibir mensagem
              run: echo "Essa é uma execução do primeiro stage no GitHub Actions."
            
    segundo-stage:
        runs-on: ubuntu-latest
        needs: [primeiro-stage]
        steps:
            - name: Segundo - Exibir mensagem
              run: echo "Essa é uma execução do segundo stage no GitHub Actions."

    terceiro-stage:
        runs-on: ubuntu-latest
        steps:
            - name: Primeiro - Exibir mensagem
              run: echo "Essa é uma execução do terceiro stage no GitHub Actions."